name: 'Install common Linux dependencies'
description: 'Common logic for Linux dependencies installation'
runs:
  using: "composite"
  steps:
    - run: |
          sudo apt-get update && sudo apt-get install -y \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          libfreetype-dev \
          libflac-dev \
          libvorbis-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libfreetype-dev \
          xvfb \
          x11-utils \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xfixes0 \
          xdotool \
          libopenal1 \
          libvorbisfile3
      shell: bash
